# BEGIN ########################## REQUIRED METADATA for Admin Setup ##############################

##### ##### ##### Super Admin Email, the account that can manage the entire CDP. 
##### The password for the super admin is set when running setup-new-leocdp.sh
superAdminEmail={{superAdminEmail}}

##### ##### ##### Data Hub for Data Observers ##### ##### ##### #####
httpObserverDomain={{httpObserverDomain}}

##### ##### ##### LEO Bot for FAQ and Content Creation ##### ##### ##### #####
httpLeoBotDomain={{httpLeoBotDomain}}
httpLeoBotApiKey={{httpLeoBotApiKey}}

##### ##### ##### Admin Dashboard ##### ##### #####
httpAdminDomain={{httpAdminDomain}}
webSocketDomain={{webSocketDomain}}
adminLogoUrl={{adminLogoUrl}} 

##### ##### ##### SMTP / Email Server ##### ##### #####
smtpHost={{smtpHost}}
smtpPort={{smtpPort}}
smtpUser={{smtpUser}}
smtpPassword={{smtpPassword}}
smtpFromAddress={{smtpFromAddress}}
smtpFromName=CDP Admin
smtpTls=true

##### ##### ##### Default CDP Database ##### ##### #####
mainDatabaseConfig=cdpDbConfigs

##### ##### ##### Database Backup Configurations ##### ##### #####
databaseBackupPeriodHours=24
databaseBackupRetentionDays=7
databaseBackupPath={{databaseBackupPath}}

# END ########################## REQUIRED METADATA for Admin Setup ##############################

############################## DEFAULT METADATA for CDP ##############################
runtimeEnvironment=PRO
minifySuffix=-min
buildEdition=PRO
buildVersion=v_0.9.0

############################################################ 
# Controls how user profiles are merged in your CDP system
#| Value        | Meaning                                                                                              |
#| ------------ | ------------------------------------------------------------------------------------------------------|
#| `automation` | Automatically merges profiles based on rules or matching keys (email, phone, etc.)                    |
#| `manually`   | Admins or operators must review and approve merges. Safer, but slower and requires human intervention.|
#| `hybrid`     | Some automatic merging occurs, but certain conflicts require manual approval.    
############################################################                     |
profileMergeStrategy=manually

##### ##### ##### CDN for Static Files ##### ##### #####
httpStaticDomain=cdn.jsdelivr.net/gh/USPA-Technology/leo-cdp-static-files@v0.9

##### ##### ##### Data Model Metadata ##### ##### #####
industryDataModels=COMMERCE,MEDIA,SERVICE,FINANCE

##### ##### ##### Runtime Path for Config Files ##### ##### #####
runtimePath=.
pathMaxmindDatabaseFile=data/GeoIP2-City-Asia-Pacific.mmdb

##### ##### ##### Default HTTP Routers ##### ##### #####
httpRoutingConfigAdmin=leocdp-admin
httpRoutingConfigObserver=datahub

##### ##### ##### Global System Configurations ##### ##### #####
messageQueueType=local
enableCachingViewTemplates=true

##### ##### ##### Apache Kafka Configurations ##### ##### #####
kafkaBootstrapServer=localhost:9092
kafkaTopicEvent=LeoCdpEvent
kafkaTopicEventPartitions=2
kafkaTopicProfile=LeoCdpProfile
kafkaTopicProfilePartitions=2

##### ##### ##### Data Policies ##### ##### #####
numberOfDaysToKeepDeadVisitor=30
maxSegmentSizeToRunInQueue=10000
batchSizeOfSegmentDataExport=300

##### ##### ##### Update Shell Script ##### ##### #####
updateShellScriptPath=
updateLeoSystemSecretKey=

##########################################################################################
