// Version: v_0.9.0_2026-07-01-09-36-30
'use strict';const eventDataTypes=[{name:"First-party Data",id:1},{name:"Second-party Data",id:2},{name:"Third-party Data",id:3}],journeyStages=[{name:"AWARENESS",id:1},{name:"ATTRACTION",id:2},{name:"ASK",id:3},{name:"ACTION",id:4},{name:"ADVOCACY",id:5}],journeyStagesMap={1:"AWARENESS",2:"ATTRACTION",3:"ASK",4:"ACTION",5:"ADVOCACY"},scoringModels=[{name:"Lead Score",id:1},{name:"Prospect Score",id:2},{name:"Engagement Score",id:3},{name:"Loyalty Score",id:12},{name:"Data Quality Score",id:4},{name:"CAC Score",
id:5},{name:"CLV Score",id:6},{name:"Credit Score",id:11},{name:"Churn Score",id:13},{name:"CES Score",id:7},{name:"CSAT Score",id:8},{name:"CFS Score",id:9},{name:"NPS Score",id:10}],initJourneyMapAndTouchpointHubs=function(){var a=$("#journeyFlowChart").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');loadJourneyMapAndTouchpointHubs(currentJourneyMapId,"#journeyFlowChart","#journeyMapName, #authorizedJourneyName","#touchpoint_hub_table",function(b,d){a.empty();5<=window.currentUserProfile.role&&
loadSystemUsersForDataAuthorization(!0,b,$("#authorizedJourneyViewers"),$("#authorizedJourneyEditors"))})},refreshJourneyMapView=function(){currentJourneyMapId&&(location.hash="#calljs-leoCdpRouter('Data_Journey_Map','"+currentJourneyMapId+"','_refresh_"+(new Date).getTime()+"')")},loadJourneyFlowReport=function(){showJourneyFlowReport({journeyMapId:currentJourneyMapId},"journeyFlowReport")},updateJourneyMap=function(a){a={touchpointHubJson:JSON.stringify($("#touchpoint_hub_table").jsGrid("option",
"data")),journeyMapId:currentJourneyMapId};LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/save",a,function(b){0===b.httpCode&&""===b.errorMessage?""!=b.data?refreshJourneyMapView():console.error("updateJourneyMap ",rs):LeoAdminApiUtil.logErrorPayload(b)})},loadFeedbackTemplateItems=function(a,b){LeoAdminApiUtil.getSecuredData("/cdp/asset-item/asset-templates",{obsid:a},function(d){cxFeedbackTemplates=d.data.cxFeedbackTemplates;landingPageTemplates=d.data.landingPageTemplates;b()})},loadEventMetrics=
function(){LeoAdminApiUtil.getSecuredData("/cdp/funnel/event-metrics",{},function(a){eventMetrics=a.data})};
var loadJourneyTemplate=function(){iziToast.info({title:"Information",message:"This function is under development and is not yet available"})},jsGridItemUrlTemplate=function(a){a=a?a.trim():"";return 0===a.indexOf("http")?(a=$("\x3ca\x3e").attr("href","javascript:").attr("title",a).attr("onclick","openUrlInNewTab(event,this)").text(a),$('\x3cdiv class\x3d"long_url_holder" \x3e\x3c/div\x3e').append(a)):$('\x3cdiv class\x3d"long_url_holder" \x3e\x3c/div\x3e').html(a)};
function initJourneyMapNameEditor(){var a="Journey Map: "+(new Date).toDateString(),b=function(c){LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/update-name",{journeyMapName:c,journeyMapId:currentJourneyMapId},function(e){0===e.httpCode&&""===e.errorMessage?(iziToast.success({title:"Data Journey Map",message:"\x3cb\x3e"+c+"\x3c/b\x3e is updated successfully!",timeout:2500}),loadJourneyMapList(!0)):LeoAdminApiUtil.logErrorPayload(e)})},d=$("#journeyMapName");d.click(editJourneyMapName);$("#journeyMapNameEditor").blur(function(){var c=
$(this).val().trim();c=""===c?a:c;$("#journeyMapNameEditor").hide();d.text()!==c?(d.text(c).show(),b(c)):d.show()});$("#journeyMapNameEditor").keyup(function(c){"13"==(c.keyCode?c.keyCode:c.which)&&(c=$(this).val().trim(),c=""===c?a:c,$("#journeyMapNameEditor").hide(),d.text()!==c?(d.text(c).show(),b(c)):d.show())})}
function saveJourneyDataAuthorization(){var a=$("#authorizedJourneyViewers").val()||[],b=$("#authorizedJourneyEditors").val()||[];a={authorizedViewers:a,authorizedEditors:b,journeyMapId:currentJourneyMapId};a.updateAllProfilesInJourney=!0===$("#updateAllProfilesInJourney").prop("checked");LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/update-data-authorization",a,function(d){d.data===currentJourneyMapId?iziToast.success({title:"Data Journey Map",message:"\x3cb\x3eThe Data Journey Authorization of "+
$("#journeyMapName").text()+"\x3c/b\x3e is updated successfully!",timeout:3E3}):LeoAdminApiUtil.logErrorPayload(d)})}function loadJourneyStagesList(a){var b=$("#journeyStagesList");journeyStages.forEach(function(d){b.append('\x3coption value\x3d"'+d.id+'" \x3e'+d.name+"\x3c/option\x3e")});b.val("1").change();b.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){"function"===typeof a&&a($(this).val())})}
function loadJourneyMapList(a,b,d,c){var e=$("#journeyMapList");!0===a&&e.find("option").remove().trigger("chosen:updated");LeoAdminApiUtil.getSecuredData("/cdp/journeymap/list",{_:(new Date).getTime()},function(f){if(0===f.httpCode&&""===f.errorMessage){f=f.data;var l=window.currentJourneyMapId;!0===d&&5<=currentUserProfile.role&&e.append('\x3coption value\x3d"" \x3e All Journey Maps \x3c/option\x3e');f.forEach(function(m){e.append('\x3coption value\x3d"'+m.id+'" \x3e'+m.name+"\x3c/option\x3e")});
e.val(l).change();"function"===typeof c&&c(e.val(),e.find("option:selected").text());e.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){if("function"===typeof b){var m=$(this).val(),k=$(this).find("option:selected").text();window.currentJourneyMapId=m;b(m,k)}else window.currentJourneyMapId=$(this).val(),refreshJourneyMapView()})}else LeoAdminApiUtil.logErrorPayload(f)})}
function loadTouchpointHubList(a,b,d,c){var e=$("#touchpointHubList");!0===b&&e.find("option").remove().trigger("chosen:updated");b=$("#journeyMapList").val();""===b&&(b="id_default_journey");LeoAdminApiUtil.getSecuredData("/cdp/touchpointhub/list",{journeyMapId:b},function(f){0===f.httpCode&&""===f.errorMessage?(f.data.forEach(function(l){e.append('\x3coption value\x3d"'+l.id+'" \x3e'+l.name+"\x3c/option\x3e")}),"string"===typeof a&&e.val(a).change(),"function"===typeof c&&c(e.val(),e.find("option:selected").text()),
e.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){if("function"===typeof d){var l=$(this).val(),m=$(this).find("option:selected").text();d(l,m)}}),$("#touchpointHubList_chosen").css("z-index","99")):LeoAdminApiUtil.logErrorPayload(f)})}function editJourneyMapName(){var a=$("#journeyMapName");$("#journeyMapNameEditor").val(a.text()).show().focus();a.hide()}
function createNewJourneyMap(){$("#dialogCreateNewJourneyMap").modal({backdrop:"static",keyboard:!1})}
function saveNewJourneyMap(){var a=$("#newJourneyMapName").val();5>=a.length?iziToast.error({title:"Journey Map Creation",message:"The journey map \x3cb\x3e"+a+"\x3c/b\x3e is too short, please enter at least 6 characters !",timeout:3E3}):($("#dialogCreateNewJourneyMap").modal("hide"),setTimeout(function(){LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/create-new",{journeyMapName:a},function(b){0===b.httpCode&&""===b.errorMessage?"string"===typeof b.data&&(currentJourneyMapId=b.data,notifySavedOK("Journey Data Map",
"The journey map \x3cb\x3e"+a+"\x3c/b\x3e has been created created successfully !"),refreshJourneyMapView()):LeoAdminApiUtil.logErrorPayload(b)})},1E3))}
function deleteCurrentJourneyMap(){if("string"===typeof currentJourneyMapId&&"id_default_journey"!=currentJourneyMapId){var a=$("#journeyMapList").find("option:checked").text();$("#delete_callback").val("");$("#confirmDeleteParentChildDialog").modal({focus:!0});$("#deleteChildItemMsg").text("Delete all touchpoint hubs and related data in this journey map!");$("#deleteChildItemCheckbox").prop("checked",!0);$("#deleteChildItem").show();var b="deleteJourneyMap"+currentJourneyMapId;window[b]=function(){var d=
baseLeoAdminUrl+"/cdp/journeymap/delete";$("#deleteChildItemCheckbox").is(":checked");LeoAdminApiUtil.callPostAdminApi(d,{journeyMapId:currentJourneyMapId},function(c){0===c.httpCode?!0===c.data?($("#deleteChildItem").hide(),$("#deleteChildItemMsg").text(""),iziToast.success({title:"OK",message:'Successfully deleted the journey map "'+a+'"',onClosing:function(e,f,l){currentJourneyMapId="id_default_journey";refreshJourneyMapView()}})):iziToast.error({title:"Error",message:c.data,onClosing:function(e,
f,l){locatio.href="/admin"}}):($("#error-on-save").html(c.errorMessage).show().delay(5E3).fadeOut("slow"),LeoAdminApiUtil.logErrorPayload(c))})};$("#delete_parent_callback").val(b);$("#deletedParentInfoTitle").text(a);$("#deletedParentInfoMsg").text("Do you want to delete the journey map ?")}}
var loadJourneyMap=function(a,b,d){LeoAdminApiUtil.getSecuredData("/cdp/journeymap/get",{id:a,_:(new Date).getTime()},function(c){if(0<c.errorCode)iziToast.error({title:"Data Journey Map",message:c.errorMessage});else{var e=c.data.journeyMap;c=e.defaultMetricName;var f=e.name,l=e.journeyStages,m=e.journeyLinks,k=e.journeyNodes;e=e.touchpointHubMap;$(d).text(f);renderJourneyFlowChart(b,c,l,k,m,e)}})};
function deleteTouchpointHubConfirmation(a,b){if(a&&b){$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});var d="deleteTouchpointHubConfirmation"+a;window[d]=function(){LeoAdminApiUtil.callPostAdminApi("/cdp/touchpointhub/delete",{id:a},function(c){0===c.httpCode&&""===c.errorMessage?iziToast.success({title:"Data Journey Map",message:b+" is deleted successfully!",timeout:3E3,onClosed:function(){refreshJourneyMapView()}}):LeoAdminApiUtil.logErrorPayload(c)})};$("#delete_callback").val(d);
$("#deletedInfoTitle").text("Touchpoint Hub Name: "+b).show();$("#deletedInfoMsg").text("Do you want to delete the selected touchpoint hub permanently?")}}const getJourneyLevelList=function(){for(var a=[],b=1;42>=b;b++)a.push({Name:"[ "+b+" ]",Id:b});return a};
var loadJourneyMapAndTouchpointHubs=function(a,b,d,c,e){LeoAdminApiUtil.getSecuredData("/cdp/journeymap/get",{id:a,_:(new Date).getTime()},function(f){if(0<f.errorCode)iziToast.error({title:"Data Journey Map",message:f.errorMessage});else{var l=f.data.touchpointHubTypes,m=f.data.journeyMap,k=m.name,g=m.defaultMetricName,n=m.journeyStages,q=m.journeyLinks,t=m.journeyNodes,u=m.touchpointHubIndex,v=m.touchpointHubMap;$(d).text(k);"function"===typeof e&&e(m,t.length);renderJourneyFlowChart(b,g,n,t,q,
v);m=[];for(k in v)g=u[k],n=v[k],n.index=g+1,m[g]=n;var w=[];Object.keys(l).forEach(h=>{var p=parseInt(h);0<p&&30!==p&&1E3>p&&w.push({typeName:l[h].replaceAll("_"," "),type:p})});k=f.canInsertData;u=f.canEditData;f=f.canDeleteData;var r=-1;$(c).jsGrid({data:m,width:"100%",height:"auto",inserting:k,editing:u,sorting:!0,paging:!1,confirmDeleting:!1,onItemInserting:function(h){h.item.totalProfile="number"===typeof h.item.totalProfile?h.item.totalProfile:0;var p=safeParseInt($(".jsgrid-grid-body tbody tr:last td:first").text())-
1;h.item.journeyLevel=p;p=h.item.type;null!=v[h.item.name]?(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:h.item.name+" is duplicated, please enter a different name !"})):0<r&&!(30===p||1E3<=p)&&(h.item.index=r,r=-1)},onItemUpdating:function(h){var p=h.item,x=p.type;p=p.name;if(30===x||1E3<=x)h.cancel=!0,iziToast.error({title:"Data Journey Map",message:p+" is read-only touchpoint, you can not update it !"})},onItemInserted:function(h){iziToast.success({title:"Data Journey Map",message:h.item.name+
" is inserted successfully!",timeout:2500,onClosed:function(){updateJourneyMap(!0)}})},onItemUpdated:function(h){iziToast.success({title:"Data Journey Map",message:h.item.name+" is updated successfully!",timeout:2500,onClosed:function(){updateJourneyMap(!1)}})},onItemDeleting:function(h){h.cancel=!0;h=h.item;var p=h.name;30!=h.type?deleteTouchpointHubConfirmation(h.id,p):iziToast.error({title:"Data Journey Map",message:p+" is read-only touchpoint hub, you can not delete it !"})},onRefreshed:function(h){var p=
h.grid._insertRow;h=h.grid._bodyGrid;console.log(p);var x=safeParseInt($(".jsgrid-grid-body tbody tr:last td:first").text())-1;$(p).find("td:first").text("["+x+"]");$("\x3ctfoot\x3e\x3c/tfoot\x3e").appendTo(h).append(p)},fields:[{name:"journeyLevel",title:"Level",type:"select",items:getJourneyLevelList(),valueField:"Id",textField:"Name",width:24},{name:"name",title:"Name",type:"text",width:60,validate:"required",align:"center",css:"touchpoint_hub_name",sorting:!1},{name:"type",title:"Type",type:"select",
items:w,valueField:"type",textField:"typeName",width:58,css:"datatable_text",insertTemplate:function(){var h=jsGrid.fields.select.prototype.insertTemplate.call(this);h.change(function(){var p=$(this).val();if(30==p||1E3<=p)iziToast.error({title:"Data Journey Map",message:"Can not select DATA OBSERVER, VISITOR REPORT, LEAD REPORT and CUSTOMER REPORT !"}),$("#touchpoint_hub_table").jsGrid("cancelEdit")});return h},editTemplate:function(h){var p=jsGrid.fields.select.prototype.editTemplate.call(this,
h);return 30==h?"DATA OBSERVER":p},itemTemplate:function(h){var p=jsGrid.fields.select.prototype.itemTemplate.call(this,h);return 30==h?"DATA OBSERVER":p}},{name:"firstPartyData",title:"First-party Data",type:"CustomCheckBox",validate:"required",width:34,align:"center",sorting:!1},{name:"totalProfile",title:"Total Profile",type:"number",width:25,editing:!1,align:"center",css:"datatable_text",insertTemplate:function(){var h=this.__proto__.insertTemplate.call(this);h.val(0);return h},itemTemplate:function(h){return"\x3cspan\x3e"+
("number"===typeof h?h:0).toLocaleString()+"\x3c/span\x3e"},validate:{validator:"range",message:function(h,p){return'The total profile should be between 0 and 1,000,000,000. Entered age is "'+h+'" is out of specified range.'},param:[0,1E9]}},{name:"url",title:"URL or Location Address",type:"text",itemTemplate:jsGridItemUrlTemplate,validate:"required",align:"center",sorting:!1},{type:"control",deleteButton:f,editButton:u,width:22,sorting:!1}]});$("#touchpoint_hub_table").jsGrid("sort","journeyLevel");
k&&u||$("#touchpoint_hub_table").find(".jsgrid-button").click(errorNoAuthorization)}})};
const getJsTrackingCodeGA4=function(){var a="",b=$("#measurement_id_GA4").val().trim();if(""!==b){var d=_.template($("#google-analytics-javascript-tpl").html());a+="\n"+d({measurementId:b})+"\n"}return""!==a?"\x3cscript\x3e"+a+"\x3c/script\x3e\n":""},getJsCodeEventTrackingFunctions=function(){var a="",b=0;eventMetrics.forEach(function(d){if(!0===d.showInObserverJS){b++;var c="#leo-tracking-view-event-code-tpl";3===d.journeyStage||4===d.journeyStage||5===d.journeyStage?c=6===d.scoreModel?"#leo-tracking-conversion-event-code-tpl":
"#leo-tracking-action-event-code-tpl":6===d.journeyStage&&(c="#leo-tracking-feedback-event-code-tpl");c=_.template($(c).html());d={counter:b,eventMetricId:d.id,eventMetricName:d.eventLabel.replaceAll(" ","")};a+=c(d)}});return a},getTrackingJsCode=function(a){var b=JSON.parse(decodeURIComponent($(a).data("json")));console.log("getTrackingJsCode ",b);var d=b.id,c=b.name,e=b.type;a=b.dataSourceUrl;b=b.javascriptTags||[];var f=0<b.length?b[0].trim():"",l=window.baseLeoObserverDomain,m=window.baseStaticDomain;
if(0<e&&12>e){$("#webDataObserverCodeDialog").modal({backdrop:"static",keyboard:!1});$("#code_holder .CodeMirror").remove();e=$("#data_observer_code")[0];var k=CodeMirror.fromTextArea(e,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});k.setSize(null,393);setTimeout(function(){var g=function(){var n=$("#leo_observer_auto_track").is(":checked"),q=$("#leo_observer_auto_collect_UTM").is(":checked"),t=$("#leo_observer_auto_collect_GA4").is(":checked"),u=$("#leo_observer_auto_track_all_links").is(":checked"),
v=$("#leo_observer_auto_track_all_buttons").is(":checked");t=t?getJsTrackingCodeGA4():"";var w=getJsCodeEventTrackingFunctions(),r=$("#webDataObserverCodeDialog .code").val().trim().replace("__leoObserverId__",d);r=r.replace("__tpHubName__",c);r=r.replace("__leoObserverDomain__",l);r=r.replace("__staticFileDomain__",m);r=r.replace("__eventTrackingFunctions__",w);r=n?q?r.replace("__autoTrackingFunctions__","LeoObserver.recordEventPageView(parseDataUTM())"):r.replace("__autoTrackingFunctions__","LeoObserver.recordEventPageView()"):
r.replace("__autoTrackingFunctions__","// No auto tracking, please call it yourself");u&&(r+="\nLeoObserver.addTrackingAllLinks();\n");v&&(r+="\nLeoObserver.addTrackingAllButtons();\n");if("string"!==typeof f||""===f)f=t+"\x3cscript\x3e\n"+r+"\n\x3c/script\x3e";k.getDoc().setValue(f);k.refresh();k.execCommand("selectAll")};$("#leo_observer_auto_track, #leo_observer_auto_collect_UTM, #leo_observer_auto_collect_GA4, #leo_observer_auto_track_all_links, #leo_observer_auto_track_all_buttons").change(function(){g()});
$("#btn_ok_auto_collect_GA4").click(function(){g()});g();addHandlerCopyCodeButton("#data_observer_code","#webDataObserverCodeDialog button.btn-copy-code")},350);e=$("#testObserverChromeExtBtn");e.attr({leoObserverId:d,leoObserverDomain:l,staticFileDomain:m,dataSourceUrl:a});e.click(function(){var g=$(this).attr("leoObserverId"),n=$(this).attr("leoObserverDomain"),q=$(this).attr("staticFileDomain"),t=$(this).attr("dataSourceUrl");t=0<t.indexOf("?")?t:t+"?";window.open(t+"_leoObserverLogDomain\x3d"+
n+"\x26_leoObserverId\x3d"+g+"\x26_leoObserverCdnDomain\x3d"+q,"_blank")})}else notifyErrorMessage("Can not get tracking code of offline touchpoint, please use QR code")},getCxFeedbackJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));var b=a.id;a=a.type;30>a?loadFeedbackTemplateItems(b,function(){if(0===$("#feedbackTemplateSelector option").length&&0<cxFeedbackTemplates.length)for(var d in cxFeedbackTemplates){var c='\x3coption value\x3d"'+d+'" \x3e'+cxFeedbackTemplates[d].title+
"\x3c/option\x3e";$("#feedbackTemplateSelector").append(c)}$("#dialogEmbeddedCxFeedbackForm").modal({backdrop:"static",keyboard:!1});$("#feedbackTemplateSelector").val("0").change();initEmbeddedFeedbackForm(b,"dialogEmbeddedCxFeedbackForm",cxFeedbackTemplates[0]);var e=$("#feedbackTemplateSelector");e.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){var f=parseInt($(this).val());initEmbeddedFeedbackForm(b,"dialogEmbeddedCxFeedbackForm",cxFeedbackTemplates[f])});
$("#leo_survey_in_shared_devices").change(function(){e.trigger("change")})}):notifyErrorMessage("Can not get feedback code for the touchpoint hub type \x3d "+a)},getWebLeadFormJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));var b=a.id,d=a.name;a=a.type;if(0<a&&12>a){$("#webLeadFormCodeDialog").modal({backdrop:"static",keyboard:!1});$("#code_holder .CodeMirror").remove();a=$("#webLeadFormCodeDialog .code")[0];var c=CodeMirror.fromTextArea(a,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,
matchBrackets:!0,readOnly:!0});c.setSize(null,480);setTimeout(function(){var e=$("#webLeadFormCodeDialog .code").val().trim().replace("__leoObserverId__",b);e=e.replace("__tpHubName__",d);e=e.replace("__LeoObserverDomain__",baseLeoObserverDomain);c.getDoc().setValue("\x3cscript\x3e\n"+e+"\n\x3c/script\x3e");c.refresh();c.execCommand("selectAll")},350)}},getQrImageFormCode=function(a){a=decodeURIComponent($(a).data("json"));a=JSON.parse(a);console.log("getQrImageFormCode ",a);var b=a.qrCodeData,d=
window.baseUploadDomain;$("#qrImageFormCodeDialog").modal({backdrop:"static",keyboard:!1});a=b.landingPageUrl;var c=b.qrCodeImage,e=b.trackingUrl;b=b.shortUrl||e.replace("/qrct/","/ct/");d="https://"+d+c.replace("./","/");$("#qrHrefUrl").attr("href",d);$("#qrImgSrc").attr("src",d);$("#qrTouchpointHubURL").val(a);$("#qrShortURL").val(b);$("#qrCodeImageURL").val(d)},getPersonalizeContentCode=function(a){$("#itemTypePersonalization").text("content");getPersonalizationCode(a,"contents")},getPersonalizeProductCode=
function(a){$("#itemTypePersonalization").text("product");getPersonalizationCode(a,"products")},getEmbeddedChatbotJsCode=function(a){},getPersonalizationCode=function(a,b){a=JSON.parse(decodeURIComponent($(a).data("json")));var d=a.id,c=a.name;a=a.type;if(0<a&&12>a){$("#dialogEmbeddedRecomender").modal({backdrop:"static",keyboard:!1});$("#dialogEmbeddedRecomender .CodeMirror").remove();a=$("#dialogEmbeddedRecomender .code")[0];var e=CodeMirror.fromTextArea(a,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,
matchBrackets:!0,readOnly:!1});e.setSize(null,480);setTimeout(function(){var f=$("#dialogEmbeddedRecomender .code").val().trim(),l="https://"+baseLeoObserverDomain+"/ris/html/"+b;f=f.replace("__observerId__",d);f=f.replace("__tpHubName__",c);f=f.replace("__personalizationUrl__",l);l="leo_recommender_"+d;e.getDoc().setValue('\x3cscript id\x3d"'+l+'"\x3e\n'+f+"\n\x3c/script\x3e");e.refresh();e.execCommand("selectAll");addHandlerCopyCodeButton("#dialogEmbeddedRecomender .code","#dialogEmbeddedRecomender button.btn-copy-code")},
500)}},showRedisSourceInfo=function(a){a=decodeURIComponent($(a).data("json"));var b=JSON.parse(a).dataSourceUrl.split("/");a=b[2];b=b[3];$("#dataSourceConfigHostAndPort").text(a);$("#dataSourceConfigTouchpointName").text(b);$("#redisSourceInfoDialog").modal({backdrop:"static",keyboard:!1})},showObserverApiInfo=function(a){a=decodeURIComponent($(a).data("json"));a=JSON.parse(a);console.log("showObserverApiInfo",a);var b=a.id;"leo_data_observer"===b?(b="default_access_key",$("#leoCdpApiTokenKey").val("default_access_key")):
$("#leoCdpApiTokenKey").val(b);var d="string"===typeof a.accessTokens[b]?a.accessTokens[b]:"";$("#leoCdpApiTokenValue").val(d);$("#leoCdpApiObserverName").text(a.name);$("#leoCdpGetProfileApiUrl").val(baseLeoObserverUrl+"/api/profile/save");$("#leoCdpTrackEventApiUrl").val(baseLeoObserverUrl+"/api/event/save");$("#leoCdpListEventsApiUrl").val(baseLeoObserverUrl+"/api/event/list?startIndex\x3d0\x26numberResult\x3d10\x26profileId\x3d{profile_ID}");$("#leoCdpWebhookUrl").val(baseLeoObserverUrl+"/webhook?tokenkey\x3d"+
b+"\x26tokenvalue\x3d"+d+"\x26source\x3d");$("#observerApiInfoDialog").modal({backdrop:"static",keyboard:!1})},resetAccessTokenForLeoObserverApi=function(){if(confirm("Would you like to reset the API access token ?")){var a=$("#leoCdpApiTokenKey").val();LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/touchpointhub/reset-access-token",{observerId:a},function(b){0===b.httpCode&&""===b.errorMessage&&(b=b.data,$("#leoCdpApiTokenKey").val(b.tokenKey),$("#leoCdpApiTokenValue").val(b.tokenValue),
iziToast.success({title:"Reset API Access Token",message:"The new API access token is generated successfully!"}))})}},initDataObserverJsGridPlugin=function(){var a=function(b){jsGrid.Field.call(this,b)};a.prototype=new jsGrid.Field({sorter:function(b,d){return 0},itemTemplate:function(b){if(""!==b.data){var d=b.data,c=b.type;b=b.firstPartyData;var e="";return 30===c?e+'\x3cdiv style\x3d"margin:68px 0;"\x3e \x3cbutton style\x3d"width:144px!important;" type\x3d"button" class\x3d"btn btn-do-now btn-get-code" onclick\x3d"showObserverApiInfo(this)"   data-json\x3d"'+
(d+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e API \x26 Webhook \x3c/button\x3e \x3c/div\x3e '):31===c?(e+='\x3cdiv style\x3d"margin:20px 0;"\x3e \x3cbutton type\x3d"button" class\x3d"btn btn-do-now btn-get-code" onclick\x3d"showRedisSourceInfo(this)" ',e+(' data-json\x3d"'+d+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Redis Information \x3c/button\x3e \x3c/div\x3e')):32===c?(e+=
'\x3cdiv style\x3d"margin:20px 0;"\x3e \x3cbutton type\x3d"button" class\x3d"btn btn-do-now btn-get-code" onclick\x3d"showKafkaSourceInfo(this)" ',e+(' data-json\x3d"'+d+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Kafka Information \x3c/button\x3e \x3c/div\x3e')):33===c?(e+='\x3cdiv style\x3d"margin:20px 0;"\x3e \x3cbutton type\x3d"button" class\x3d"btn btn-do-now btn-get-code" onclick\x3d"getQrImageFormCode(this)" ',e+(' data-json\x3d"'+
d+'" \x3e\x3ci class\x3d"fa fa-qrcode" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Get QR Code \x3c/button\x3e \x3c/div\x3e')):loadObserverActionButtons(b,c,d)}return""},insertTemplate:function(b){return this._insertCode=b},editTemplate:function(b){return this._editCode=b},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.LeoDataObserver=a},loadObserverActionButtons=function(a,b,d){function c(l,m,k){f.push("\x3cli\x3e"+buildButton(l,
m,k,e)+"\x3c/li\x3e")}const e=escapeHtmlAttr(d),f=[];c("fa-qrcode","QR Image Code","getQrImageFormCode");a&&(0<b&&12>b?(c("fa-code","Track User Events","getTrackingJsCode"),c("fa-code","Collect Feedback","getCxFeedbackJsCode"),c("fa-code","Recommend Content","getPersonalizeContentCode"),c("fa-code","Recommend Products","getPersonalizeProductCode"),c("fa-code","Add Chat Assistant","getEmbeddedChatbotJsCode")):c("fa-code","Survey Rating Forms","getCxFeedbackJsCode"));c("fa-info-circle","Developer API",
"showObserverApiInfo");return'\x3cdiv class\x3d"btn-group"\x3e\x3cbutton type\x3d"button" class\x3d"btn btn-primary dropdown-toggle" data-toggle\x3d"dropdown"\x3e\x3ci class\x3d"fa fa-code" aria-hidden\x3d"true"\x3e\x3c/i\x3e Get Code\x3c/button\x3e\x3cbutton type\x3d"button" class\x3d"btn btn-primary dropdown-toggle" data-toggle\x3d"dropdown"\x3e\x3cspan class\x3d"caret"\x3e\x3c/span\x3e\x3c/button\x3e\x3cul class\x3d"dropdown-menu" role\x3d"menu"\x3e'+f.join("")+"\x3c/ul\x3e\x3c/div\x3e"};
function buildButton(a,b,d,c){return'\x3cbutton type\x3d"button" class\x3d"btn btn-do-now btn-sm btn-get-code" onclick\x3d"'+d+'(this)" data-json\x3d"'+c+'"\x3e\x3ci class\x3d"fa '+a+'" aria-hidden\x3d"true"\x3e\x3c/i\x3e '+b+"\x3c/button\x3e"}function escapeHtmlAttr(a){return a?String(a).replace(/&/g,"\x26amp;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;"):""}
const showDataObserverTable=function(a){var b=a.data.eventObservers;a=a.data.touchpointHubTypes;for(var d=0;d<b.length;d++){var c=b[d];c.index=d+1;var e=a[c.type];c.typeName=e;var f=c.firstPartyData,l=c.type;e={id:c.id,name:c.name,type:l,typeName:e};e.collectDirectly=c.collectDirectly;e.qrCodeData=c.qrCodeData;e.accessTokens=c.accessTokens;e.securityCode=c.securityCode;e.dataSourceUrl=c.dataSourceUrl;e.javascriptTags=c.javascriptTags;e=JSON.stringify(e);c.observerModel={type:l,data:encodeURIComponent(e),
firstPartyData:f}}$("#data_observers_table").empty().jsGrid({data:b,width:"100%",height:"auto",scroll:!0,inserting:!1,editing:!1,sorting:!1,paging:!1,onRefreshed:function(){$(".jsgrid-grid-body").css("min-height","380px");console.log("showDataObserverTable length "+b.length)},fields:[{name:"journeyLevel",title:"Level",type:"select",items:getJourneyLevelList(),valueField:"Id",textField:"Name",width:24},{name:"name",title:"Name",type:"string",align:"center",css:"observer_name"},{name:"id",title:"Unique ID",
type:"string",width:68,align:"center",css:"observer_id"},{name:"firstPartyData",title:"First-party Data",type:"CheckBoxIcon",width:40,align:"center"},{name:"collectDirectly",title:"Tracking directly",type:"CheckBoxIcon",width:40,align:"center"},{name:"dataSourceUrl",title:"URL",type:"UrlLink",width:120,align:"center",css:"observer_url"},{name:"observerModel",title:"Actions",type:"LeoDataObserver",width:72,align:"center"}]}).jsGrid("sort","journeyLevel")},initDataObserverList=function(){initDataObserverJsGridPlugin();
$("#txt_filter_keywords_observers").keypress(function(a){"13"==(a.keyCode?a.keyCode:a.which)&&(a=$(this).val().trim(),0<a.length?filterDataObserverList(a):loadDataObserverList())});loadDataObserverList()},loadDataObserverList=function(){$("#txt_filter_keywords_observers").val("");LeoAdminApiUtil.getSecuredData("/cdp/observers",{journeyMapId:currentJourneyMapId},showDataObserverTable)},filterDataObserverList=function(a){LeoAdminApiUtil.getSecuredData("/cdp/observers",{journeyMapId:currentJourneyMapId,
filterKeywords:a},showDataObserverTable)},loadDataJourneyMapsByFilter=function(a,b,d,c,e,f,l){var m=[{data:"name"},{data:"authorizedViewers"},{data:"authorizedEditors"},{data:"createdAt"},{data:"updatedAt"},{data:"defaultMetricName"}],k=getUserSession();if(k)return $(c).DataTable({lengthMenu:[[20,30,40],[20,30,40]],processing:!0,serverSide:!0,searching:!0,search:{return:!0},ordering:!0,serverMethod:"POST",ajax:{url:baseLeoAdminUrl+"/cdp/journeymaps/filter",contentType:"application/json",beforeSend:function(g){$(d).show();
$(b).hide();g.setRequestHeader("leouss",k)},data:function(g){var n=g.order[0];g.sortField=m[n.column].data;g.sortAsc="asc"===n.dir;g.searchValue=g.search.value;delete g.order;delete g.search;"function"===typeof e&&(g=e(g),$(c).data("authorizedViewer",g.authorizedViewer),$(c).data("authorizedEditor",g.authorizedEditor));return JSON.stringify(g)},dataSrc:function(g){var n=g.canInsertData,q=g.canEditData,t=g.canDeleteData;$(c).data("canInsertData",n);$(c).data("canEditData",q);$(c).data("canDeleteData",
t);"function"===typeof loadDataCallback&&loadDataCallback(g);$(d).hide();$(b).show();return g.data}},columnDefs:[{render:function(g,n,q){return'\x3cdiv class\x3d"highlight_text text-center" title\x3d"'+g+'" \x3e'+textTruncate(g,150)+"\x3c/div\x3e"},targets:0,orderable:!1},{render:function(g,n,q){n=$(c).data("authorizedViewer");g=g.includes(n);n=q.id+"-viewer";"object"===typeof f&&(f[q.id]=g);return getTableRowCheckedBox(a,c,n,g)},targets:1},{render:function(g,n,q){n=$(c).data("authorizedEditor");
g=g.includes(n);n=q.id+"-editor";"object"===typeof l&&(l[q.id]=g);return getTableRowCheckedBox(a,c,n,g)},targets:2},{render:function(g,n,q){return'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff;" \x3e'+moment.utc(g).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/div\x3e"},targets:3},{render:function(g,n,q){return'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff;" \x3e'+moment.utc(g).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/div\x3e"},targets:4},{render:function(g,n,q){return'\x3cdiv class\x3d" text-center"  \x3e'+
g+"\x3c/div\x3e"},targets:5},{render:function(g,n,q){return'\x3ca class\x3d"control" title\x3d"Segment Report" href\x3d"#calljs-leoCdpRouter(\'Data_Journey_Map\',\''+(q.id+'\')" \x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e View\x3c/a\x3e')},targets:6}],columns:m})};
var loadJourneyMapEventMatrix=function(a,b,d,c,e){b={journeyMapId:b||"",beginFilterDate:d||"",endFilterDate:c||""};d=baseLeoAdminUrl+"/cdp/analytics360/event-matrix";$("#"+a).html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(d,b,function(f){var l=f.data;"object"===typeof l?(renderMatrixChart("Event Matrix Report",a,l.xLabels,l.yLabels,l.dataList),"function"===typeof e&&e(l)):console.error(f)})};
const loadJourneyTouchpointHubReport=function(a,b){$("#journeyObserverChart").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/touchpoint-hub-report",{journeyMapId:a,maxTouchpointHubSize:b},function(d){if(0===d.httpCode&&""===d.errorMessage)if(d=d.data,0<d.length){var c=[],e=[];d.forEach(function(f){c.push(f.name);e.push(f.eventCount)});renderHorizontalBarChart("journeyObserverChart",c,e)}else $("#journeyObserverChart").html('\x3cdiv class\x3d"alert alert-info" role\x3d"alert"\x3e No data available \x3c/h4\x3e');
else LeoAdminApiUtil.logErrorPayload(d)})};function showJourneyFlowReport(a,b){var d=$("#"+b).empty().html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e'),c=baseLeoAdminUrl+"/cdp/analytics360/touchpoint-flow-report";a.startIndex=0;a.numberFlow=200;LeoAdminApiUtil.getSecuredData(c,a,function(e){0===e.httpCode&&""===e.errorMessage?(d.empty(),flowNetworkGraph=renderDirectedGraph(b,{nodes:e.data.nodes,edges:e.data.edges},e.data.rootNodeId)):LeoAdminApiUtil.logErrorPayload(e)})}
function setJourneyFlowGraphView(){"object"===typeof flowNetworkGraph&&setTimeout(function(){flowNetworkGraph.fit(!0)},300)}
function loadJourneyGraph(){(new JourneyFlowGraph("journeyFlowReport",{avgPageview:25,avgPurchase:10})).render({nodes:[{data:{id:"google",label:"Google",image:"https://cdn-icons-png.flaticon.com/128/281/281764.png",type:"touchpoint_3rdparty"}},{data:{id:"youtube",label:"YouTube",image:"https://cdn-icons-png.flaticon.com/128/3670/3670147.png",type:"touchpoint_3rdparty"}},{data:{id:"tiktok",label:"TikTok",image:"https://cdn-icons-png.flaticon.com/128/3669/3669950.png",type:"touchpoint_3rdparty"}},{data:{id:"website",
label:"Website",image:"https://cdn-icons-png.flaticon.com/128/1927/1927746.png",type:"touchpoint_1stparty"}},{data:{id:"customer_service",label:"Customer Service",image:"https://cdn-icons-png.flaticon.com/128/1028/1028011.png",type:"touchpoint_1stparty"}},{data:{id:"facebook",label:"Facebook",image:"https://cdn-icons-png.flaticon.com/128/5968/5968764.png",type:"touchpoint_3rdparty"}},{data:{id:"customer_lead",label:"Customer Lead",image:"https://cdn-icons-png.flaticon.com/128/950/950237.png",type:"cdp_profile"}},
{data:{id:"engaged_customer",label:"Engaged Customer",image:"https://cdn-icons-png.flaticon.com/128/4149/4149882.png",type:"cdp_profile"}}],edges:[{data:{source:"google",target:"youtube",weight:0}},{data:{source:"google",target:"tiktok",weight:0}},{data:{source:"google",target:"website",weight:31}},{data:{source:"tiktok",target:"website",weight:27}},{data:{source:"youtube",target:"website",weight:31}},{data:{source:"youtube",target:"facebook",weight:43}},{data:{source:"engaged_customer",target:"customer_service",
weight:3}},{data:{source:"facebook",target:"customer_lead",weight:12}},{data:{source:"customer_lead",target:"website",weight:6}},{data:{source:"website",target:"engaged_customer",weight:21}}]})}
const loadBehavioralEventList=function(){var a=function(d){d={eventMetricJson:JSON.stringify(d)};LeoAdminApiUtil.callPostAdminApi("/cdp/funnel/event-metric/save",d,function(c){0===c.httpCode&&""===c.errorMessage?""!=c.data?location.reload(!0):console.error("saveEventMetricMetaData ",rs):LeoAdminApiUtil.logErrorPayload(c)})},b=function(d){$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});if("string"===typeof d){var c="deleteEventMetricMetaData"+d;window[c]=function(){LeoAdminApiUtil.callPostAdminApi("/cdp/funnel/event-metric/delete",
{eventName:d},function(e){0===e.httpCode&&""===e.errorMessage?setTimeout(function(){location.reload(!0)},700):LeoAdminApiUtil.logErrorPayload(e)})};$("#delete_callback").val(c);$("#deletedInfoTitle").text("Event Metric: "+d).show();$("#deletedInfoMsg").text("Delete Data Confirmation")}};LeoAdminApiUtil.getSecuredData("/cdp/funnel/metadata",{},function(d){var c=d.canInsertData,e=d.canDeleteData;d.canEditData||$("button.data-control").attr("disabled","disabled");var f=d.data.behavioral_metrics,l=f[0]?
f[0].flowName:"general_business_event";d=d.data.general_data_funnel;let m=!0;$("#togglePaginationBtn").click(function(){m=!m;$("#event_metrics_table").jsGrid("option","paging",m);m?($(this).html('\x3ci class\x3d"fa fa-list"\x3e\x3c/i\x3e Show All Records'),$(this).removeClass("btn-primary").addClass("btn-outline-primary")):($(this).html('\x3ci class\x3d"fa fa-file-text"\x3e\x3c/i\x3e Enable Pagination'),$(this).removeClass("btn-outline-primary").addClass("btn-primary"))});$("#event_metrics_table").jsGrid({width:"100%",
height:"auto",inserting:c,confirmDeleting:e,editing:!0,sorting:!0,filtering:!1,paging:!0,pageSize:15,pageButtonCount:5,data:f,deleteConfirm:function(k){return k.systemMetric?"The event metric \x3cb\x3e["+k.eventName+"]\x3c/b\x3e is the \x3cb\x3eevent metric of system\x3c/b\x3e. You can not delete this metric.":"The event metric ["+k.eventName+"] will be removed. Are you sure ?"},onItemInserting:function(k){f.some(function(g){return g.eventName===k.item.eventName.trim()})?(k.cancel=!0,iziToast.info({title:"Info",
message:"The event ["+k.item.eventName+"] already exists in the metric list!"})):(k.item.systemMetric=!1,k.item.dataType=1,k.item.flowName=l)},onItemInserted:function(k){var g=k.item;""===g.eventName.trim()||""===g.eventLabel.trim()?k.cancel=!0:a(k.item)},onItemEditing:function(k){k.item.systemMetric&&iziToast.info({title:"Information Box",message:"The event \x3cb\x3e["+k.item.eventName+"]\x3c/b\x3e is an event metric of the system. Be careful when you edit this metric!",timeout:5E3})},onItemUpdated:function(k){a(k.item)},
onItemDeleting:function(k){k.item.systemMetric&&(k.cancel=!0)},onRefreshed:function(k){$("input.jsgrid-insert-mode-button").click(function(){$("tr.jsgrid-insert-row").find('input[type\x3d"number"]').val(0)})},fields:[{name:"eventName",title:"Event Name",align:"center",type:"text",validate:"required",filtering:!0},{name:"eventLabel",title:"Event Label",align:"center",type:"text",validate:"required",filtering:!0},{name:"score",title:"Event Score",type:"number",align:"center",width:40,validate:"required",
filtering:!0},{name:"cumulativePoint",title:"Loyalty Points",type:"number",width:44,align:"center",validate:"required",filtering:!0},{name:"funnelStageId",title:"Default Funnel Stage",type:"select",items:d,valueField:"id",textField:"name",filtering:!0},{name:"scoreModel",title:"Scoring Model",type:"select",items:scoringModels,width:80,valueField:"id",textField:"name",filtering:!0},{name:"journeyStage",type:"select",title:"CX Journey Stage",items:journeyStages,align:"center",width:74,valueField:"id",
textField:"name",filtering:!0},{name:"showInObserverJS",title:"Enable Tracking",type:"CustomCheckBox",width:48,align:"center",filtering:!1},{type:"control",width:70,editButton:!0,deleteButton:!0,itemTemplate:function(k,g){jsGrid.fields.control.prototype.itemTemplate.apply(this,arguments);var n=g.systemMetric,q=g.eventName;var t="Edit Event Name: "+q;$("\x3cbutton\x3e").data("eventName",q).attr({class:"jsgrid-custom-button",title:t}).html('\x3ci class\x3d"fa fa-cogs event-set-rules" style\x3d"" aria-hidden\x3d"true"\x3e\x3c/i\x3e').click(function(v){console.log("setRules button ",
$(this).data("eventName"));underDevelopment(this);v.stopPropagation()});var u="customGridEditbutton jsgrid-button jsgrid-edit-button";t=$("\x3cbutton\x3e").data("eventName",q).attr({class:u,title:"Edit Event Metric"}).click(function(v){console.log("Edit button ",$(this).data("eventName"))});u="customGridDeletebutton jsgrid-button jsgrid-delete-button";q=$("\x3cbutton\x3e").data("eventName",q).attr({class:u,title:"Delete Event Metric"}).click(function(v){var w=$(this).data("eventName");n?iziToast.info({title:"Information Box",
message:"The event \x3cb\x3e["+w+"]\x3c/b\x3e is the \x3cb\x3eevent metric of system\x3c/b\x3e. You can not delete this metric !"}):b(w);v.stopPropagation()});u=$("\x3cdiv\x3e");n?u.attr("title","Event metric of system"):(u.addClass("editable_event_metric"),u.attr("title","Click to edit or delete"));u.append(t).append(q);return u}}]})})};