'use strict';var dataServiceStatusReadyHtml='\x3ci class\x3d"fa fa-check-square" aria-hidden\x3d"true" style\x3d"font-size:1.1em"\x3e\x3c/i\x3e The service is active',dataServiceMap={},renderAgent=function(a){var b=$("#agents_holder").empty().show();dataServiceMap={};_.forEach(a,function(c,e){e=c.id;dataServiceMap[e]=c;var d=!1;c.configs.service_api_key&&""!=c.configs.service_api_key?(c.service_api_key=c.configs.service_api_key.substr(0,5)+"...",d=!0):c.service_api_key="";var f=_.template($("#tpl_agent_view").html());
b.append(f(c));b.find("i.config_description").tooltip();d&&($("#service_box_"+e).addClass("active_service_box"),$("#service_box_header_"+e).addClass("config_ready"));1===c.status&&(d=dataServiceStatusReadyHtml,null!=c.startedAt&&(d+=" and working "),$("#"+e+"_api_key_label").html(d).addClass("config_ready"))});$("#services_tooltip").tooltip()},dataServiceLoader=function(a,b,c,e,d,f,g,h){a={keywords:a,filterServiceValue:b,startIndex:f,numberResult:g};a.forPersonalization=c;a.forDataEnrichment=e;a.forSynchronization=
d;LeoAdminApiUtil.getSecuredData("/cdp/agent/list",a,function(k){"function"===typeof h&&"object"===typeof k.data&&h(k.data)})},loadAgents=function(a,b){$("#agents_pagination").empty();$("#agents_loader").show();$("#agents_holder").hide();$("#filter_agents_keywords").on("keyup",function(f){13===f.keyCode&&loadAllAgents()});var c=!0,e=!0,d=!0;"active_for_personalization"===b?d=e=!1:"active_for_enrichment"===b?d=c=!1:"active_for_synchronization"===b&&(c=e=!1);dataServiceLoader(a,b,c,e,d,0,1E4,function(f){$("#agents_loader").hide();
0<f.length?$("#agents_pagination").pagination({dataSource:f,className:"paginationjs paginationjs-big",pageSize:6,callback:function(g,h){renderAgent(g)},beforePageOnClick:function(){}}):$("#agents_holder").show().html('\x3cdiv class\x3d"col-lg-12 row highlight_text"\x3e \x3ch3 style\x3d"text-align: center;" \x3eNo results found !\x3c/h3\x3e \x3c/div\x3e')})};function resetAgentFilter(){$("#filter_agents_keywords").val("");$("#select_filter_agents").val("all");loadAllAgents()}
function loadAllAgents(){var a=$("#filter_agents_keywords").val(),b=$("#select_filter_agents").val();loadAgents(a,b)}
function saveAgentInfo(a){a=$(a).data("id");var b=dataServiceMap[a];b.name=$("#dataServiceName").val().trim();b.dagId=$("#dataServiceDagId").val().trim();b.description=$("#dataServiceDescription").val().trim();b.forDataEnrichment=$("#forDataEnrichment").prop("checked");b.forPersonalization=$("#forPersonalization").prop("checked");b.forSynchronization=$("#forSynchronization").prop("checked");var c={};$("#dataServiceConfigList div.config_item").each(function(){var d=$(this).find('input[name\x3d"configName"]').val(),
f=$(this).find('input[name\x3d"configValue"]').val(),g=$(this).find('input[name\x3d"configValue"]').attr("type");0<d.length&&(c[d]="number"===g&&0<f.length?parseInt(f):f)});b.configs=c;b.status=$("#dataServiceStatus").prop("checked")?1:0;if(""===b.name)notifyErrorMessage("Service name is empty, please enter a name");else{var e=function(d){null!=d?(notifySavedOK("Activation Data Service",'The data of "\x3cb\x3e'+b.name+'\x3c/b\x3e" has been saved successfully'),$("#dialogSetAgentInfo").modal("hide"),
loadAgents()):console.error("saveAgentInfo ",d)};LeoAdminApiUtil.callPostAdminApi("/cdp/agent/save",{objectJson:JSON.stringify(b)},function(d){0===d.httpCode&&""===d.errorMessage?e(d.data):LeoAdminApiUtil.logErrorPayload(d)},e)}}function newAgent(){LeoAdminApiUtil.getSecuredData("/cdp/agent/get",{dataServiceName:"",dataServiceId:""},function(a){a=a.data;showAgentDialog(a);dataServiceMap[a.id]=a})}
function loadAgent(a){var b=dataServiceMap[a];"object"===typeof b?showAgentDialog(b):notifyErrorMessage("Can not load data for service: "+a)}
function resetAgent(a){var b=function(e){$("#"+e+"_api_key").val("");$("#"+e+"_api_url").val("");var d=dataServiceMap[e];_.forOwn(d.configs,function(g,h){d.configs.service_api_url="";d.configs.service_api_key="";d.startedAt=null});d.status=0;var f=function(g){null!=g?(iziToast.success({title:"Data Service",message:"The config of \x3cb\x3e"+d.name+"\x3c/b\x3e is reset OK!",timeout:3E3}),loadAgents()):console.error("resetAgent ",g)};e={objectJson:JSON.stringify(d)};LeoAdminApiUtil.callPostAdminApi("/cdp/agent/save",
e,function(g){0===g.httpCode&&""===g.errorMessage?f(g.data):LeoAdminApiUtil.logErrorPayload(g)},f)};$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});if(a){var c="resetAgent_"+a;window[c]=function(){b(a)};$("#delete_callback").val(c);$("#deletedInfoTitle").text("Service ID: "+a).show();$("#deletedInfoMsg").text("Do you want to reset API Key and API URL of data service permanently?")}}
function deleteAgent(a){$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});if(a){var b="deleteAgent_"+a;window[b]=function(){LeoAdminApiUtil.callPostAdminApi("/cdp/agent/delete",{dataServiceId:a},function(c){0===c.httpCode&&""===c.errorMessage?c.data===a?(iziToast.success({title:"Data Service",message:"The service \x3cb\x3e"+a+"\x3c/b\x3e is successfully deleted!",timeout:3E3}),loadAgents()):console.error("deleteAgent ",c):LeoAdminApiUtil.logErrorPayload(c)})};$("#delete_callback").val(b);
$("#deletedInfoTitle").text("Service ID: "+a).show();$("#deletedInfoMsg").text("Do you want to delete the selected service permanently?")}}
function showAgentDialog(a){if("string"!==typeof a.id)notifyErrorMessage("Invalid data service: "+a);else{$("#dialogSetAgentInfo").modal({backdrop:"static",keyboard:!1});var b=a.id;$("#dataServiceSaveButton").data("id",b);$("#dataServiceName").val(a.name);$("#dataServiceDescription").val(a.description);$("#dataServiceDagId").val(a.dagId||"");$("#dataServiceStatus").prop("checked",1==a.status);$("#forPersonalization").prop("checked",a.forPersonalization);$("#forDataEnrichment").prop("checked",a.forDataEnrichment);
$("#forSynchronization").prop("checked",a.forSynchronization);$("#dataServiceConfigList").empty();var c=0;_.forOwn(a.configs,function(e,d){var f=(new Date).getTime()+c;c++;addNewConfigForAgent(b,{serviceId:b,configName:d,configValue:e,time:f})})}}
function addNewConfigForAgent(a,b){var c=(new Date).getTime()+randomInteger(0,1E4);a=null!=b?b:{serviceId:a,configName:"",configValue:"",time:c};console.log(a);a.inputType="number"===typeof a.configValue?"number":"text";b=_.template($("#tpl_config_row_item").html());$("#dataServiceConfigList").append(b(a)).find("input:last").focus()}function deleteConfigOfAgent(a){$("#"+a).remove()};