// Version: v_0.9.0_2025-11-30-17-24-50
'use strict';const EXPIRED_AFTER_21_DAYS=30240,EXPIRED_AFTER_1_HOUR=60;function getUrlParams(a){a=a?(new URL(a)).search:window.location.search;a=new URLSearchParams(a);const b={};for(const [c,d]of a.entries())b[c]=d;return b}
const loadSystemUserLoginSession=function(){LeoAdminApiUtil.callPostApi(baseLeoAdminUrl+"/user/login-session",{},function(a){0===a.httpCode&&""===a.errorMessage?(loginFormHandler(a.data.userSession),a="data:image/png;base64,"+a.data.captchaImage,$("#captcha_img").show().attr("src",a),$("#system_user_login_loader").hide(),$("#system_user_login_div").show()):LeoAdminApiUtil.logErrorPayload(a)})},loginFormHandler=function(a){var b=function(){var c=baseLeoAdminUrl+"/user/check-login",d=$("#username").val(),
e=$("#password").val(),g=$("#captcha").val();d={userlogin:d,userpass:e,usersession:a,captcha:g};$("#info-login").html("\x3cb\x3eSending data ...\x3c/b\x3e").show();LeoAdminApiUtil.callPostApi(c,d,function(h){if(""===h.errorMessage){var k=h.data;lscache.set("usersession",a,EXPIRED_AFTER_21_DAYS);lscache.set("encryptionkey",k,EXPIRED_AFTER_21_DAYS);$("#system_user_login_form, #btn_system_login").hide();$("#info-login").html('\x3ci class\x3d"fa fa-check-circle fa-2" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3cb\x3e Login successfully ! \x3c/b\x3e ');
setTimeout(function(){window.location.reload()},3E3)}else $("#info-login").hide(),$("#error-login").html('\x3ci class\x3d"fa fa-exclamation-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '+h.errorMessage).show().delay(5E3).fadeOut(),setTimeout(function(){LeoAdminApiUtil.logErrorPayload(h)},2E3)})};$("#btn_system_login").click(b);$("#username").on("keyup",function(c){13===c.keyCode&&$("#password").focus()});$("#password").on("keyup",function(c){13===c.keyCode&&$("#captcha").focus()});$("#captcha").on("keyup",
function(c){13===c.keyCode&&b()})},loadLoginSessionSSO=function(){var a=ssoSessionUrl+"?_t\x3d"+(new Date).getTime();$("#sso_login_url").attr("href",a);showDefaultLogin&&$("#default_login_url").show();LeoAdminApiUtil.callPostApi(baseLeoAdminUrl+"/user/login-session",{sso:!0},function(b){0===b.httpCode&&""===b.errorMessage?(loadCheckSSO(b.data.ssoUserEmail,b.data.ssoUserSession,b.data.userSession),$("#system_user_login_loader").hide(),$("#system_user_login_div").show()):LeoAdminApiUtil.logErrorPayload(b)})},
doSSOlogout=function(a){ssoLogoutUrl&&a&&0<=ssoLogoutUrl.indexOf("http")?location.href=ssoLogoutUrl+"?sid\x3d"+a+"\x26t\x3d"+(new Date).getTime():console.error(ssoLogoutUrl,a.ssoLogoutUrl)},loadCheckSSO=function(a,b,c){if(0<a.length&&0<b.length){$("#email").val(a);$("#email_panel").show();$("#sso_login_url, #default_login_url").hide();var d=baseLeoAdminUrl+"/user/check-sso";a={ssoUserEmail:a,usersession:c};$("#info-login").html("\x3cb\x3eChecking data ...\x3c/b\x3e").show();LeoAdminApiUtil.callPostApi(d,
a,function(e){if(""===e.errorMessage){var g=e.data;lscache.set("ssousersession",b,EXPIRED_AFTER_1_HOUR);lscache.set("usersession",c,EXPIRED_AFTER_1_HOUR);lscache.set("encryptionkey",g,EXPIRED_AFTER_1_HOUR);$("#system_user_login_form, #btn_system_login").hide();$("#info-login").html('\x3ci class\x3d"fa fa-check-circle fa-2" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3cb\x3e Login successfully ! \x3c/b\x3e ');setTimeout(function(){window.location.reload()},3E3)}else $("#info-login").hide(),$("#error-login").html('\x3ci class\x3d"fa fa-exclamation-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '+
e.errorMessage).show().delay(5E3).fadeOut(),setTimeout(function(){LeoAdminApiUtil.logErrorPayload(e)},2E3)})}},initSystemUserLogin=function(a){$("#login_logo").attr("src",window.pageHeaderLogo).show();var b=lscache.get("usersession"),c=lscache.get("encryptionkey");"string"===typeof b&&"string"===typeof c?console.log("You login OK with session "+b):(!0===a?loadLoginSessionSSO():loadSystemUserLoginSession(),console.log("loadSystemUserLoginSession is called "))},loadSystemEventsTable=function(a,b,c,
d,e,g,h){var k=getUserSession();if(k){a=_.template($("#system-event-table-tpl").html())({eventObjectName:a});$("#"+b).empty().html(a);var n=[{data:"createdAt"},{data:"action"},{data:"accessIp"},{data:"userAgent"},{data:"data"}];h="object"===typeof h?h:[20,30,40];return $("#system_event_table").DataTable({lengthMenu:[h,h],lengthChange:1<h.length?!0:!1,processing:!0,serverSide:!0,searching:!1,search:{return:!1},ordering:!0,serverMethod:"POST",ajax:{url:baseLeoAdminUrl+"/cdp/system-control/action-logs",
contentType:"application/json",beforeSend:function(f){$("#system_event_loader").show();$("#system_event_list").hide();f.setRequestHeader("leouss",k)},data:function(f){f.objectName=c;f.objectId=d;f.action="";f.accessIp="";f.requestUserLogin=e;var l=f.order[0];f.sortField=n[l.column].data;f.sortAsc="asc"===l.dir;f.searchValue=f.search.value;delete f.order;delete f.search;return JSON.stringify(f)},dataSrc:function(f){var l=f.canInsertData,m=f.canEditData,p=f.canDeleteData;$("#system_event_table").data("canInsertData",
l);$("#system_event_table").data("canEditData",m);$("#system_event_table").data("canDeleteData",p);$("#system_event_loader").hide();$("#system_event_list").show();"function"===typeof g&&g();return f.data}},columnDefs:[{render:function(f,l,m){return'\x3cdiv class\x3d"text-center" style\x3d"color:#3300ff; width:78px; margin: auto;" \x3e\x3cmark\x3e'+toLocalDateTime(f)+"\x3c/mark\x3e\x3c/div\x3e"},targets:0},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.9em; width:180px; text-align:center; margin: auto;word-wrap: break-word;" \x3e\x3cmark\x3e'+
f+"\x3c/mark\x3e\x3c/div\x3e"},targets:1,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.9em; text-align:center; margin: auto; word-wrap: break-word;"\x3e\x3cmark\x3e'+f+"\x3c/mark\x3e\x3c/div\x3e"},targets:2,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.8em; text-align:center; width:260px; margin: auto; word-wrap: break-word;" \x3e'+f+"\x3c/div\x3e"},targets:3,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.78em; word-wrap: break-word; width:400px; margin: auto;" \x3e'+
textTruncate(f,300)+"\x3c/div\x3e"},targets:4,orderable:!1}],columns:n,order:[[0,"desc"]]})}},loadSystemEventsFromLoginUser=function(a){return loadSystemEventsTable("User Login","panel_login_account_view_logs","SystemUser","",a)};
var loadSystemInfoConfigs=function(){LeoAdminApiUtil.getSecuredData("/cdp/system-config/list-all",{},function(a){var b=$("#system_configs_holder");_.forEach(a.data,function(c,d){d=c.id;systemConfigMap[d]=c;c.disabledText=c.configs.read_only?"disabled":"";if("string"===typeof c.description&&"string"===typeof c.configs.service_api_url){var e=_.template($("#tpl_system_config_box").html());b.append(e(c));"local-system"===c.configs.service_api_url&&$("#"+d+"_buttons_div").find("button").attr("disabled",
"disabled");1===c.status&&$("#"+d+"_api_url_div").addClass("highlight_text")}});b.find("div.active_false button").attr("class","btn btn-default").attr("disabled","disabled");b.find("div.panel_active_false").find("input").attr("disabled","disabled");b.find("i.config_description").tooltip();a=_.map(systemConfigMap.profile_data_fields.coreFieldConfigs,function(c,d){return 0<c.dataQualityScore?(c.coreAttribute=!0,c):!1});a=_.filter(a,function(c){return!1!==c});a=_.sortBy(a,[function(c){return c.identityResolution?
1E3*c.dataQualityScore:c.dataQualityScore}]).reverse();$("#profileAttributeCount").text(a.length);renderProfileMetaDataTable(a)})};
function renderProfileMetaDataTable(a){$("#profile_metadata_table").jsGrid({data:a,width:"100%",height:"auto",inserting:!1,editing:!0,sorting:!0,paging:!1,confirmDeleting:!0,deleteConfirm:function(b){return b.coreAttribute?"The attribute \x3cb\x3e["+b.attributeName+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute.":"The attribute ["+b.attributeName+"] will be removed. Are you sure ? "},onItemInserting:function(b){},onItemInserted:function(b){},onItemEditing:function(b){},
onItemUpdated:function(b){var c=b.item;console.log(c);b=systemConfigMap.profile_data_fields;var d=b.coreFieldConfigs[c.attributeName];d&&(d.dataQualityScore=c.dataQualityScore,b={objectJson:JSON.stringify(b)},LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",b,function(e){0===e.httpCode&&""===e.errorMessage?notifySuccessMessage("The attribute \x3cb\x3e["+c.attributeName+"]\x3c/b\x3e is saved successfully !"):LeoAdminApiUtil.logErrorPayload(e)}))},onItemDeleting:function(b){},onRefreshed:function(b){},
fields:[{name:"identityResolution",title:"Identity Resolution Key",align:"center",type:"CheckBoxIcon",width:64,sorter:"string",editTemplate:function(b){return'\x3cdiv class\x3d"text-center"\x3e'+getCheckedBoxIcon(b)+"\x3c/div\x3e"}},{name:"attributeName",title:"Attribute Name",align:"center",type:"text",validate:"required",validate:"required",editing:!1},{name:"label",title:"Label",align:"center",type:"text",validate:"required",width:120,editing:!1},{name:"type",title:"Data Type",align:"center",type:"text",
validate:"required",editing:!1,itemTemplate:function(b,c){c=b.lastIndexOf(".")+1;b=0<c?b.substr(c):b;return'\x3cdiv class\x3d"profile_field_type"\x3e '+b+" \x3c/div\x3e"}},{name:"dataQualityScore",title:"Data Quality Score",type:"number",align:"center",width:76,validate:"required",itemTemplate:function(b,c){return 0<b?'\x3cdiv class\x3d"highlight_text positive_dqs"\x3e '+b+" \x3c/div\x3e":0>b?'\x3cdiv class\x3d"highlight_text negative_dqs"\x3e '+b+" \x3c/div\x3e":b}},{name:"synchronizable",title:"Synchronizable ",
align:"center",type:"CustomCheckBox",width:64,validate:"required",sorter:"string"},{title:"Controls",type:"control",width:80,editButton:!0,deleteButton:!1,itemTemplate:function(b,c){jsGrid.fields.control.prototype.itemTemplate.apply(this,arguments);var d=c.coreAttribute,e=c.attributeName;var g="Edit Event Name: "+e;$("\x3cbutton\x3e").data("attributeName",e).attr({class:"jsgrid-custom-button",title:g}).html('\x3ci class\x3d"fa fa-cogs event-set-rules" style\x3d"" aria-hidden\x3d"true"\x3e\x3c/i\x3e').click(function(k){console.log("setRules button ",
$(this).data("attributeName"));underDevelopment(this);k.stopPropagation()});var h="customGridEditbutton jsgrid-button jsgrid-edit-button";g=$("\x3cbutton\x3e").data("attributeName",e).attr({class:h,title:"Edit Attribute"}).click(function(k){console.log("Edit button ",$(this).data("attributeName"))});h="customGridDeletebutton jsgrid-button jsgrid-delete-button";e=$("\x3cbutton\x3e").data("attributeName",e).attr({class:h,title:"Delete Attribute"}).click(function(k){var n=$(this).data("attributeName");
d?notifyErrorMessage("The attribute \x3cb\x3e["+n+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute."):deleteEventMetricMetaData(n);k.stopPropagation()});h=$("\x3cdiv\x3e");d?h.attr("title","The attribute of system"):(h.addClass("editable_profile_attribute"),h.attr("title","Click to edit or delete"));h.append(g).append(e);return h}}]})}
function callDataQualityComputeJob(){LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/call-data-quality-compute-job",{},function(a){0===a.httpCode&&""===a.errorMessage?notifySuccessMessage("\x3cb\x3eCall Data Quality Compute Job\x3c/b\x3e is called successfully!"):LeoAdminApiUtil.logErrorPayload(a)})}
function callSystemControlUpgrade(){notifySuccessMessage("The process to upgrade system is started");LeoAdminApiUtil.callPostAdminApi("/cdp/system-control/upgrade",{},function(a){0===a.httpCode&&""===a.errorMessage?($("#upgrade_system_logs").val(a.data),notifySuccessMessage("upgrade system is done, please wait for 10 seconds and reload page",function(){setTimeout(function(){location.reload(!0)},9999)})):LeoAdminApiUtil.logErrorPayload(a)})}
function resetSystemServiceInfo(a){var b=systemConfigMap[a];b.status=0;_.forOwn(b.configs,function(d,e){"string"===typeof d&&(b.configs[e]="")});$("#"+a+"_api_url").val("");$("#"+a+"_api_url_div").removeClass("highlight_text");$("#systemServiceStatus").prop("checked",!1);var c=function(d){null!=d?iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+b.name+"\x3c/b\x3e is reset successfully !",timeout:3E3}):console.error("saveSystemServiceInfo ",d)};a={objectJson:JSON.stringify(b)};
LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",a,function(d){0===d.httpCode&&""===d.errorMessage?c(d.data):LeoAdminApiUtil.logErrorPayload(d)},c)}
function saveSystemServiceInfo(a){var b=$(a).data("id"),c=systemConfigMap[b],d={};$("#systemServiceConfigList input").each(function(){var g=$(this).attr("name"),h=$(this).attr("type");d[g]="number"===h?parseInt($(this).val()):"checkbox"===h?$(this).prop("checked"):$(this).val()});c.configs=d;c.status=$("#systemServiceStatus").prop("checked")?1:0;a={objectJson:JSON.stringify(c)};var e=function(g){null!=g?($("#dialogSetSystemConfigs").modal("hide"),iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+
c.name+"\x3c/b\x3e is saved OK!",timeout:3E3}),g=d.service_api_url,$("#"+b+"_api_url").val(g)):console.error("saveSystemServiceInfo ",g)};LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",a,function(g){0===g.httpCode&&""===g.errorMessage?e(g.data):LeoAdminApiUtil.logErrorPayload(g)},e)}
function setSystemServiceInfo(a){var b=systemConfigMap[a];$("#dialogSetSystemConfigs").modal({backdrop:"static",keyboard:!1});$("#systemServiceName").text(b.name);$("#systemServiceDescription").text(b.description);$("#systemServiceSaveButton").data("id",a);$("#systemServiceStatus").prop("checked",b.status);var c=$("#systemServiceConfigList");c.empty();_.forOwn(b.configs,function(d,e){var g={inputName:e};g.inputType="number"===typeof d?"number":"boolean"===typeof d?"checkbox":"text";var h=_.template($("#tpl_config_row_item").html());
c.append(h(g));"checkbox"===g.inputType?c.find('input[name\x3d"'+e+'"]').prop("checked",d):c.find('input[name\x3d"'+e+'"]').val(d)})};