// Version: v_0.9.0_2026-01-09-17-45-32
'use strict';const USING_LEO_BOT_WITH_AI=""!==dnsDomainLeoBot,LEOBOT_URL_ASK=baseLeoBotUrl+"/_leoai/ask",LEOBOT_URL_GET_INFO=baseLeoBotUrl+"/_leoai/visitor-info";var leoBotActionList=[];leoBotActionList.push({text:"Search profile",value:"Search profile",icon:"search"});USING_LEO_BOT_WITH_AI&&(leoBotActionList.push({text:"Ask question",value:"Ask question",icon:"question-circle"}),leoBotActionList.push({text:"Create content",value:"Create content",icon:"file-word-o"}));
leoBotActionList.push({text:"Create short URL",value:"Create short URL",icon:"link"});leoBotActionList.push({text:"Help me",value:"Help me",icon:"info-circle"});window.leoBotUI=!1;function getBotUI(){!1===window.leoBotUI&&(window.leoBotUI=new BotUI("LEO_ChatBot_Container"));return window.leoBotUI}var notifyLeoBotOk=function(){notifySuccessMessage("\x3cb\x3e The AI ChatBot \x3c/b\x3e is ready !");$("#menu_ai_chatbot").show()};
function checkLeoBotIsServerReady(b,a=null,c=null){if(USING_LEO_BOT_WITH_AI){var e=new URLSearchParams({visitor_id:b,_:Date.now()});a&&e.append("name",a);c&&e.append("touchpoint_id",c);$.getJSON(`${LEOBOT_URL_GET_INFO}?${e.toString()}`,function(d){0===d.error_code?notifyLeoBotOk():updateVisitorProfileAndActivateLeoBot(b)})}}
function updateVisitorProfileAndActivateLeoBot(b){1===currentUserProfile.status&&LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/user/activate-leobot",{visitorId:b},function(a){a.data?notifyLeoBotOk():LeoAdminApiUtil.logErrorPayload(a)})}
function initLeoChatBot(b){$("#leoChatBotDialog").modal({backdrop:"static",keyboard:!1});getBotUI().action.hide();getBotUI().message.removeAll();$("#leobot_persona").show();LeoObserverProxy.synchLeoVisitorId(function(a){window.currentUserProfile&&(window.currentUserProfile.profileVisitorId=a,leoBotSayHello())})}
var closeLeoChatBotDialog=function(){getBotUI().action.hide();getBotUI().message.removeAll().then(function(){$("#leoChatBotDialog").modal("hide")})},leoBotDoAction=function(b){var a=b.value;b="\x3cb\x3e"+a+"\x3c/b\x3e";getBotUI().message.add({human:!0,content:b,type:"html"}).then(function(){"Create short URL"===a?showChatBotLoader().then(function(c){leoBotCreateShortUrl(function(){getBotUI().message.remove(c)})}):"Help me"===a?leoBotHelpUser():"Search profile"===a?leoBotSearchProfiles():"Create content"===
a?leoBotCreateContent():"Create slides"===a?leoBotCreateSlides():leoBotPromptQuestion()})},leoBotSayHello=function(){var b="Hello "+currentUserProfile.displayName+", how can I help you ?";getBotUI().message.bot(b).then(function(){return getBotUI().action.button({delay:1E3,addMessage:!1,action:leoBotActionList})}).then(function(a){leoBotDoAction(a)})},leoBotPromptQuestion=function(b){getBotUI().action.text({delay:"number"===typeof b?b:800,action:{icon:"question-circle",cssClass:"leobot-question-input",
value:"",placeholder:"Give me a question"}}).then(function(a){a=a.value;leoBotAskServer("ask",a,a)})},leoBotCreateContent=function(){var b=function(c){getBotUI().message.bot(c.text);c=c.value;if("content-as-asset"===c){var e=function(d){getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the purpose of content"}}).then(function(f){leoBotAskServer("content",d,"Write a blog post about "+d,", the purpose of blog post is "+f.value)})};
getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the title of content"}}).then(function(d){e(d.value)})}else"content-for-segment"===c&&getBotUI().action.select({action:{placeholder:"Select Language",value:"TR",searchselect:!0,label:"text",options:[{value:"EN",text:"English"},{value:"ES",text:"Español"},{value:"TR",text:"Türkçe"},{value:"DE",text:"Deutsch"},{value:"FR",text:"Français"},{value:"IT",text:"Italiano"}],button:{icon:"check",
label:"OK"}}}).then(function(d){console.log(d.value)})},a=[];a.push({text:"Create content as digital asset",value:"content-as-asset",icon:"file-word-o"});a.push({text:"Create content for all profiles in a segment",value:"content-for-segment",icon:"file-word-o"});getBotUI().message.bot("Please select an option").then(function(){return getBotUI().action.button({delay:100,addMessage:!1,action:a})}).then(function(c){b(c)})},leoBotCreateSlides=function(){var b=function(a){getBotUI().action.text({delay:500,
action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the number of slides in presentation"}}).then(function(c){var e=parseInt(c.value);isNaN(e)?leoBotShowInfo(c.value+" is not a number !",function(){b(a)}):leoBotAskServer("presentation",a,'Create a presentation slide, just text and no images, with the title is "'+a+'" '," in "+e+' slides. Every slide must begin with the prefix "## " ',"markdown")})};getBotUI().action.text({delay:500,action:{icon:"question-circle",
cssClass:"leobot-question-input",value:"",placeholder:"Give me a title of presentation slide"}}).then(function(a){b(a.value)})},leoBotHelpUser=function(){var b=Handlebars.compile($("#tpl_leocdp_documents").html())({});USING_LEO_BOT_WITH_AI?leoBotShowAnswer("html",b,leoBotPromptQuestion):leoBotShowAnswer("html",b)},leoBotSearchProfiles=function(){getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",placeholder:"Give me a name, email address or phone number of customer"}}).then(function(b){b=
Base64.encode(b.value);location.hash="calljs-leoCdpRouter('Customer_Profile_Search','"+b+"')";closeLeoChatBotDialog()})},leoBotCreateShortUrl=function(b){LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/asset-group/list-by-asset-type",{assetType:"15"},function(a){b();"object"===typeof a.data[0]?(a=a.data[0],a=leoCdpRouterParams(["",a.id,a.categoryIds[0]]),location.hash="calljs-leoCdpRouter('Asset_Short_Link_Editor','"+a+"')",closeLeoChatBotDialog()):LeoAdminApiUtil.logErrorPayload(a)})},
leoBotCreateNewItem=function(b,a,c){var e=function(){$("#asset_item_title").val(a).focus();var d=window.trixElement;"object"===typeof d&&"content"===b?d.editor.loadHTML(c):"presentation"===b&&"function"===typeof formatMarkdownToPresentation&&formatMarkdownToPresentation(c)};LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/asset-group/get-default",{context:b},function(d){0===d.httpCode&&""===d.errorMessage?(d=d.data,newAssetItemEditor(d.assetType,d.id,d.categoryIds[0]),setTimeout(e,2E3)):LeoAdminApiUtil.logErrorPayload(d)})},
processMessageNode=function(b){var a="m_"+getRandomStrWithTime();if(0<=b.indexOf("\x3chtml\x3e"))return b=document.createElement("iframe"),b.setAttribute("id",a),b.style.width="100%",b.style.height="400px",b.style.border="1px solid #ddd",b.style.borderRadius="6px",{html:b.outerHTML,type:"iframe",id:a};var c=document.createElement("span");c.setAttribute("id",a);c.innerHTML=marked.parse(b);return{html:c.outerHTML,type:"span",id:a}};
function getRandomStrWithTime(b=10){let a="";for(let c=0;c<b;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));b=Date.now().toString(36);return`${a}_${b}`}
var leoBotShowAnswer=function(b,a,c){var e="",d="leobot-answer";if("markdown"===b)e='\x3ctextarea style\x3d"width: 100%; height: 220px;" readonly\x3d""\x3e '+a+"\x3c/textarea\x3e",d="leobot-answer-in-markdown";else{var f=processMessageNode(a);e=f.html}console.log("leoBotShowAnswer",b);getBotUI().message.add({human:!1,cssClass:d,content:e,type:"html"}).then(function(){if("iframe"===f.type){var m=document.getElementById(f.id);const g=m.contentDocument||m.contentWindow.document;g.open();g.write(a);g.close();
$(m).parent().parent().removeClass("botui-message-content").addClass("botui-message-report")}$("div.botui-message").find("a").each(function(){$(this).attr("target","_blank");var g=$(this).attr("href");0>g.indexOf("google.com")&&(g="https://www.google.com/search?q\x3d"+encodeURIComponent($(this).text()));$(this).attr("href",g)});c()})},leoBotShowInfo=function(b,a){getBotUI().message.add({human:!1,cssClass:"chatbot-info",content:b}).then(function(){a()})},leoBotAskServer=function(b,a,c,e,d){"string"===
typeof e&&(c+=e);var f="string"===typeof d?d:"html",m=parseFloat($("#leobot_creativity_score").val());if(1<a.length&&"exit"!==a){var g=function(k){"ask"===b?leoBotShowAnswer(f,k,function(){leoBotPromptQuestion(200<k.length?3E3:1E3)}):leoBotShowAnswer(f,k,function(){var h="Would you like to write a blog post?";"presentation"===b&&(h="Would you like to create a presentation slide ?");getBotUI().message.bot(h).then(function(){return getBotUI().action.button({delay:1E3,action:[{text:"Yes",value:"yes"},
{text:"No",value:"no"}]})}).then(function(l){"yes"===l.value?getBotUI().message.bot("Okay").then(function(){closeLeoChatBotDialog();leoBotCreateNewItem(b,a,k)}):closeLeoChatBotDialog()})})};showChatBotLoader().then(function(k){var h={prompt:c,question:a,context:"agent"};h.visitor_id=currentUserProfile.profileVisitorId;h.answer_in_format=f;h.temperature_score=m;h.persona_id=$("#leobot_persona").val();LeoAdminApiUtil.callPostApi(LEOBOT_URL_ASK,h,function(l){getBotUI().message.remove(k);"string"===typeof l.answer?
g(l.answer):l.error?(notifyErrorMessage(l.answer),closeLeoChatBotDialog()):notifyErrorMessage("LEO BOT is getting a system error !")},closeLeoChatBotDialog)})}else closeLeoChatBotDialog()},showChatBotLoader=function(){return getBotUI().message.add({loading:!0,content:""})},recommendContentIdeas=function(b){b=document.getElementById("suggestedVideoTpl").innerHTML;b=Handlebars.compile(b)({title:"My New Post",body:"This is my first post!"});getBotUI().message.bot({delay:500,content:b});setTimeout(function(){$("#suggestedVideoCarousel").on("slid.bs.carousel",
function(){var a=getActiveVideoInfo();console.log(a);$("#playlist_holder").empty();leoPlayVideoReport(a.video)})},500)};function getRandomInt(b,a){b=Math.ceil(b);a=Math.floor(a);return Math.floor(Math.random()*(a-b+1))+b}
function leoPlayVideoReport(b){var a=getRandomInt(1,1E5)+"_"+(new Date).getTime(),c=document.createElement("div");c.setAttribute("id",a);c.setAttribute("class","videoholder");document.getElementById("playlist_holder").appendChild(c);MediaPlayerOne.create(!0,a,b,"",[],3,[],function(e){setTimeout(function(){e.muted(!1)},1E3)})}function getActiveVideoInfo(){var b=$("#suggestedVideoCarousel .active"),a=b.data("title");b=b.data("video");return{title:a,video:b}};